apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xreadonly.aws.cast.ai
spec:
  group: aws.cast.ai
  names:
    kind: XReadOnly
    plural: xreadonly
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                forProvider:
                  type: object
                  description: Defines the castai integration
                  properties:
                    clusterName:
                      type: string
                      description: "EKS ClusterName"
                    region:
                      type: string
                      description: "Region for this EKS Cluster"
                    accountId:
                      type: string
                      description: "AWS AccountId for this EKS Cluster"
                    deleteNodesOnDisconnect:
                      type: boolean
                      description: "Delete Nodes on Disconnect"
                    assumeRoleArn:
                      type: string
                      description: "assumeRoleArn for this EKS Cluster Access for castai"
                  required:
                    - accountId
                    - clusterName
                    - region
                providerConfigRef:
                    type: object
                    description: "providerConfigRef sets the providerConfig to be used"
                    properties:
                      name:
                        type: string
                        description: "ProviderConfig reference name"
                    required:
                      - name
                deletionPolicy:
                  type: string
                  description: DeletionPolicy specifies what will happen to the underlying external when this managed resource is deleted - either "Delete" or "Orphan" the external resource.
              required:
                - forProvider
                - deletionPolicy
                - providerConfigRef
            status:
              description:  status represents the observed state of cast.ai onboarding.
              properties:
                onboarding:
                  description: Freeform field containing information about the onboarding configured by this Setup.
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
              type: object
